name: 💡 Feature Request
description: Suggest an idea or feature for Synthetic Data Studio
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make Synthetic Data Studio better!
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Is your feature request related to a problem or limitation?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe what you would like to see happen.
      placeholder: Add support for Parquet direct export in the browser / add Hugging Face export directly...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
